"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { AdminPage } from "@/components/admin/admin-page";
import { createSupabaseBrowserClient } from "@/lib/supabase/browser";
type Notice={id:string;title:string;body:string;expires_at:string|null;is_urgent:boolean;is_published:boolean;published_at:string};
export default function AdminNoticesPage(){const[items,setItems]=useState<Notice[]>([]);const[edit,setEdit]=useState<Notice|null>(null);const[status,setStatus]=useState("");
const load=useCallback(async()=>{const{data,error}=await createSupabaseBrowserClient().from("notices").select("id,title,body,expires_at,is_urgent,is_published,published_at").order("published_at",{ascending:false});if(error)setStatus(error.message);else setItems((data??[])as Notice[]);},[]);useEffect(()=>{load();},[load]);
async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);const db=createSupabaseBrowserClient();const{data:{user}}=await db.auth.getUser();const row={title:f.get("title"),body:f.get("body"),expires_at:f.get("expires")||null,is_urgent:f.get("urgent")==="on",is_published:f.get("published")==="on"};const request=edit?db.from("notices").update(row).eq("id",edit.id):db.from("notices").insert({...row,created_by:user?.id});const{data,error}=await request.select("id,title,body,expires_at,is_urgent,is_published,published_at").single();if(error||!data){setStatus(error?.message??"Unable to save notice.");return;}setItems(current=>[...current.filter(item=>item.id!==data.id),data as Notice].sort((a,b)=>b.published_at.localeCompare(a.published_at)));setEdit(null);form.reset();setStatus("Notice saved.");}
async function remove(item:Notice){if(!confirm(`Delete "${item.title}"?`))return;const{error}=await createSupabaseBrowserClient().from("notices").delete().eq("id",item.id);if(error){setStatus(error.message);return;}setItems(current=>current.filter(x=>x.id!==item.id));setStatus("Notice deleted.");}
return <AdminPage title="Notices" description="Create, edit, publish/unpublish, and delete notices."><div className="grid gap-6 xl:grid-cols-[26rem_1fr]"><form key={edit?.id??"new"} onSubmit={save} className="grid h-fit gap-3 rounded-xl bg-white p-5 shadow-sm"><h2 className="font-bold">{edit?"Edit notice":"New notice"}</h2><label>Title<input required name="title" defaultValue={edit?.title} className="mt-1 w-full rounded border p-2"/></label><label>Message<textarea required name="body" rows={6} defaultValue={edit?.body} className="mt-1 w-full rounded border p-2"/></label><label>Expiry<input name="expires" type="datetime-local" defaultValue={edit?.expires_at?.slice(0,16)} className="mt-1 w-full rounded border p-2"/></label><label><input name="urgent" type="checkbox" defaultChecked={edit?.is_urgent}/> Urgent</label><label><input name="published" type="checkbox" defaultChecked={edit?.is_published??true}/> Published</label><div className="flex gap-2"><button className="rounded bg-blue-700 px-4 py-2 font-bold text-white">Save</button>{edit&&<button type="button" onClick={()=>setEdit(null)} className="rounded border px-4 py-2">Cancel</button>}</div>{status&&<p role="status">{status}</p>}</form><section className="overflow-x-auto rounded-xl bg-white p-5 shadow-sm"><table className="w-full min-w-150 text-sm"><thead><tr className="bg-slate-100"><th className="p-3">Date</th><th>Title</th><th>Published</th><th>Actions</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td className="border-t p-3">{x.published_at.slice(0,10)}</td><td className="border-t p-3">{x.title}</td><td className="border-t p-3">{x.is_published?"Yes":"No"}</td><td className="border-t p-3"><button onClick={()=>setEdit(x)} className="mr-3 text-blue-700">Edit</button><button onClick={()=>remove(x)} className="text-red-700">Delete</button></td></tr>)}</tbody></table></section></div></AdminPage>;}
